name: PluginMc_V1
author: Cyberdelta88
main: fr.cyberdelta88.PluginMCtest.Main
version: 0.1
description: C'est un plugin de test

commands:
  title:
  animation:
  reloadconfig:
  armorstand:
  troll:
  setrdmdata:
  testconfig:
  gui :
    aliases: [GUI, guis]
  namemc :
  quoi :
  katana :